// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmJMM2Sq3j7myfUPwswjZ9SVJm2dE5pQo',
    appId: '1:106133439146:web:60c0a0436ceb85d9f5c6d3',
    messagingSenderId: '106133439146',
    projectId: 'clinichealth-9864a',
    authDomain: 'clinichealth-9864a.firebaseapp.com',
    storageBucket: 'clinichealth-9864a.firebasestorage.app',
    measurementId: 'G-3RYBS707TM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWMcOqx_4EdvpuBJfHP5I6N40GmxGuZzw',
    appId: '1:106133439146:android:b7d92b919299c8baf5c6d3',
    messagingSenderId: '106133439146',
    projectId: 'clinichealth-9864a',
    storageBucket: 'clinichealth-9864a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs1xlJokIZDpZSWudLJqy3OeafK_kB2Kc',
    appId: '1:106133439146:ios:537a049f2486e042f5c6d3',
    messagingSenderId: '106133439146',
    projectId: 'clinichealth-9864a',
    storageBucket: 'clinichealth-9864a.firebasestorage.app',
    iosBundleId: 'com.example.clinichealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs1xlJokIZDpZSWudLJqy3OeafK_kB2Kc',
    appId: '1:106133439146:ios:537a049f2486e042f5c6d3',
    messagingSenderId: '106133439146',
    projectId: 'clinichealth-9864a',
    storageBucket: 'clinichealth-9864a.firebasestorage.app',
    iosBundleId: 'com.example.clinichealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmJMM2Sq3j7myfUPwswjZ9SVJm2dE5pQo',
    appId: '1:106133439146:web:448d7b05f7de7f47f5c6d3',
    messagingSenderId: '106133439146',
    projectId: 'clinichealth-9864a',
    authDomain: 'clinichealth-9864a.firebaseapp.com',
    storageBucket: 'clinichealth-9864a.firebasestorage.app',
    measurementId: 'G-7NWVRRVN3Y',
  );
}
